import os

SUPABASE_URL='https://oupeqhpmxafjjtzkylav.supabase.co'
SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91cGVxaHBteGFmamp0emt5bGF2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTI4NjM2MywiZXhwIjoyMDU2ODYyMzYzfQ.8YDjwZKAQFkO4cJFqmF_ygWdrzdfEE8O7SQakrkrdQw'
